name: NetTango
dependencies:
      
transformers:
- $dart2js:
    checked: true
    minify: true
    verbose: true
    analyzeAll: true
    suppressWarnings: false
    suppressHints: false
    terse: false
