name: NetTango

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  dnd: ^1.4.3

dev_dependencies:
  build_runner: '>=1.10.0'
  build_web_compilers: '>=2.11.0'
  build_test: '>=1.2.0'
  test: '>=1.15.1'
