name: NetTango

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  dnd: ^1.4.3

dev_dependencies:
  build_runner: '>=1.7.2'
  build_web_compilers: '>=2.7.1'
  build_test: '>=0.10.9'
  test: '>=1.9.4'
